### ISSUE TITLE
ngrok client settings incompatible with twurple ngrok

### ISSUE THREAD

**Issue by MrDrummer** [twurple/twurple#286] opened 2021-08-31 12:24 UTC
## Bug Report
Adding a token to an independent ngrok instance will get picked up by twurple eventsub and cause the application to hang.
### Code
```ts
const eventSubListener = new EventSubListener({
  adapter: new NgrokAdapter(),
  apiClient: apiClientEventSub,
  secret: "secrethere"
})
await eventSubListener.listen()
```

### Expected behavior

Twurple ngrok to cope with user tokens applied via an independent ngrok client.

### Actual Behavior

The process hangs on `eventSubListener.listen()`

### Explanation

The ngrok client I have is a simple `.exe`. It saves settings to `C:/users/<user>/.ngrok2`.
The Twurple ngrok must detect the same config file in some capacity.

If the config file includes the `authtoken`, the process hangs. If I remove the config file, it is back to normal.
Example ngrok config file:
```yaml
authtoken: myauthtokenhere
```
also see: https://ngrok.com/docs#tunnel-definitions

You get an authtoken by signing up to their site in order to get a static subdomain.

### Reproduction

1. Download ngrok from https://ngrok.com/download
2. Sign up to ngrok
3. Run `./ngrok.exe authtoken <token>`
4. A config file will have generated in `C:/users/<user>/.ngrok2`
5. Attempt to run a bot with eventsub
6. The awaited `EventSubListener.listen()` process will hang.

### Environment

- Version: `@twurple/eventsub-ngrok: 5.0.0-pre.15` (Haven't tested for any other ngrok packages)
- Node version: 12.18.2
- Operating system: Windows 10 Pro build 19041

**Comment by d-fischer** [comment] 2021-09-02 20:25
I can not reproduce this. I logged in with an auth token and then I still can't bind a fixed subdomain. Moreover, listening works just fine.

Do you depend on a paid ngrok plan? If so, I may be unable to reproduce this at all, and you may have to debug this by yourself in order to get it fixed in this lib.

**Comment by d-fischer** [comment] 2021-11-02 23:06
Closed for inactivity. Please comment if you have more insight on this.

**Closed by d-fischer** 2021-11-02 23:06 UTC
Labels: bug, requires feedback
