### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by raziEiL** [twurple/twurple#254] opened 2021-04-10 07:49 UTC
If you create ChatClient instance of channel that was banned the application is crashes . You can use `r6female_ru1` channel name to test this case.  
 
> (node:3540) UnhandledPromiseRejectionWarning: Error: Did not receive a reply to join #r6female_ru1 in time; assuming that the join failed
>     at Timeout._onTimeout (c:\Users\denis\Documents\GitHub\ubot\node_modules\twitch-chat-client\lib\ChatClient.js:473:36)
>     at listOnTimeout (internal/timers.js:554:17)
>     at processTimers (internal/timers.js:497:7)

### Environment

- Version: 4.5.5
- Node version: v14.15.5
- Operating system: Win 10 x64

**Comment by d-fischer** [comment] 2021-05-03 22:38
This happens on all channels that are unavailable to join, even complete nonsense names.

It is caused by the promise-based nature of the client and thus can not be fixed in a backwards compatible fashion.

In the meantime, a possible workaround would be to use the `join` method instead of the `channels` option in order to be able to catch the promise rejection.

**Closed** 2021-07-25 20:46 UTC
Labels: bug, semver-major
